import Head from 'next/head'
import Image from 'next/image'
import Order from '../components/orders'
import styles from '../styles/Home.module.css'
import OrderList from "../components/orderList"
import UsersCard from '../components/usersCard'
import RegistrationCard from '../components/registrationCard'
import LogIn from '../components/logIn'
import { Provider } from 'react-redux'
import {store} from "../store/"
import 'bootstrap/dist/css/bootstrap.min.css';
import MainContainer from '../components/mainContainer'
import { Container, Navbar } from 'react-bootstrap'
import { NavigationBar } from './../components/NavigationBar';
import { FooterBar } from '../components/footerBar'

export default function Home() {
  console.log('NEXT_PUBLIC_ENV_VARIABLE',process.env.NEXT_PUBLIC_ENV_VARIABLE)
  return (
    <div className={styles.container}>
      
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar >
        <Container >
          <Navbar.Brand>
            <div className="text-decoration-none text-white"></div>
          </Navbar.Brand>
        </Container>
      </Navbar>
      <NavigationBar/>
      <main className={styles.main}>        
        <Provider store={store}>
            <MainContainer/>
          </Provider>
      </main>

      <footer className={styles.footer}>
        <a
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />

          </span>
        </a>
       
      </footer>
      <FooterBar />
    </div>
  )
}
